### ISSUE TITLE
trouble getting File->Compile Code to work

### ISSUE THREAD

**Issue by darrencruse** [jpaulm/drawfbp#27]
from doing the tutorial things overall worked out but couldn't get the compile to work from inside DrawFBP so I just compiled my files separately from the command line.

I did set JAVA_HOME before starting drawfbp
(and then later I tried setting CLASSPATH too but that didn't help)

<img width="717" alt="Screen Shot 2019-07-04 at 7 28 10 AM" src="https://user-images.githubusercontent.com/1283688/60673995-bbf3f880-9e3e-11e9-9d5f-a43dfd0d195e.png">

**Comment by jpaulm** [comment]
I think this is due to the fact that you don't appear to have a ".src"
directory in your source - I thought I had taken care of that case, but I
didn't test it as all my projects use the ".src" convention!   My bad!   If
".src" does appear in the full source file name, I change it to ".bin" for
the compile output.

I will fix that and test it in the next few days, so, in the meanwhile, you
could either do standalone compiles, or change your directory structure...
    .

Sorry about the oversight!

Regards,

Paul M.

**Comment by jpaulm** [comment]
I have put up a new copy of v2.16.15 - please give it a try!  If you don't have ".src" in the file path, the class file will go into the same directory as the source.

Regards,

P.

**Comment by darrencruse** [comment]
Hi Paul I did pull down your v2.16.15 jar and try it but I got the same error :(

(for the heck of it I tried adding the "src" directory still no luck but maybe I misunderstood the convention)

**Comment by jpaulm** [comment]
Hi Darren, sorry to be obtuse, but *I still don't know what the error is
that you ran into*!  I have said this several times, so I would really
appreciate it if you could spell it out (again...?)!

Regards,

Paul
