### ISSUE TITLE
Filling in C# classes for a network using C#FBP

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/drawfbp#62]
Hi @bergm , looking at my latest code, I see that I recently dropped some of the C# function... My question is: do you expect the Choose Component function to find C# classes? I think I had that in earlier versions, but probably only using your local C# classes (i.e. not from a DLL)... More research needed, I guess!

I am opening this as a new issue...

**Comment by bergm** [comment]
I'm not sure of what Choose Component function you are talking about. Right now I don't use some of the drawFBP functionality which might really run the flow. But I attach (for code generation) the C# classes to a component. But they are at the moment just .cs files and not from a dll. But for the moment that's ok as I anyway are basically testing and evaluating some things (and FBP). So I don't have a large library of components which for a normal user would be already compiled and possibly ready to run. I actually copy the necessary parts of the generated code right now manually into my classes representing the flow.

**Comment by jpaulm** [comment]
See my comment in the release description...  Can we close this?!

**Comment by bergm** [comment]
Yes, seams to work. I'm fine atm with having .cs files as attached code. I'm anyway using my own csharpfbp version at the moment because of .NET5. But for testing things that's actually quite nice, because I can more easily debug the components. So IMO, you can close the issue. Thank you very much for your fast response and fixes. Highly appreciated.

**Comment by jpaulm** [comment]
You're welcome - I really appreciate your reporting errors or problems to me!  Based on the number of problems you ran into, it seems to me that relatively few people are actually using DrawFBP... 

Can I ask what kinds of changes did you have to make to csharpfbp to support .NET5 - I hadn't heard of it, but then I don't do much work with C#...

I will close this issue - thanks again!

**Comment by bergm** [comment]
Regarding .NET5: I'm no .net expert, so this might not be completely true. But I didn't manage to have support for .netcore/5 in your original project. So I just copied everything and started with new Visual studio projects (with a .netcore3.1 dependency and later moved to .net5). As far as I remember I didn't change much, but I would have to compare against the original code. But besides that I wanted/needed to integrate C# FBP with the C# CapnProto version and for that I needed async/await support. So I basically just copied the Go method in network.cs and created an async version of that. You can look at it at https://github.com/zalf-rpm/csharpfbp . This is in no way ready to be taken serious! But because I copied everything I didn't offer a pull request to you (yet). Also I'm not sure FBP fits my needs perfectly (besides me wanting that :-). That's why I'm still experimenting. I also joined the Slack channel, in case you want more details.

**Comment by jpaulm** [comment]
Thanks, Michael!  I'll take a look, and maybe do some compares!  PS Feel free to send any problems, suggestions, questions, etc.!

Regards,

Paul
